// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuwfaljqzvjbxhhrjara.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1d2ZhbGpxenZqYnhoaHJqYXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTgxMzksImV4cCI6MjA2NTQ5NDEzOX0.NPEwA1RA6aSQsbgPDEl1JIm9wJioPIoriVVw83HVMi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);